from enum import Enum
from typing import Any

class Event(Enum):
    ARGS: Any = ...
    VALIDATE: Any = ...
    PERM: Any = ...
    PRE: Any = ...
    ON: Any = ...
    EXTN: Any = ...
    SOFT: Any = ...
    DIFF: Any = ...
    SYS_DOCS: Any = ...

class DELETE_STRATEGY(Enum):
    SOFT_SKIP_SYS: Any = ...
    SOFT_SYS: Any = ...
    FORCE_SKIP_SYS: Any = ...
    FORCE_SYS: Any = ...

class LOCALE_STRATEGY(Enum):
    DUPLICATE: Any = ...
    NONE_VALUE: Any = ...

class NAWAH_VALUES(Enum):
    NONE_VALUE: Any = ...
